# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'Somari.xcworkspace'

target 'Somari' do
  project 'Somari/Somari.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Somari
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'SomariTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SomariUITests' do
    # Pods for testing
  end

end

target 'SomariCore' do
  project 'SomariCore/SomariCore.xcodeproj'
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'SomariCoreTests' do
    inherit! :search_paths
  end
end
