# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

workspace 'Somari.xcworkspace'

install! 'cocoapods', generate_multiple_pod_projects: true, incremental_installation: true, integrate_targets: false

inhibit_all_warnings!
use_modular_headers!

use_frameworks!

target 'SomariCore' do
  project 'SomariCore/SomariCore.xcodeproj'

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'SomariCoreTest' do
    inherit! :search_paths
  end
end

pod 'SwiftLint'
